# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipes.ui'
#
# Created: Mon Feb 23 13:25:13 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(746, 586)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.conf_record_name = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_record_name.sizePolicy().hasHeightForWidth())
        self.conf_record_name.setSizePolicy(sizePolicy)
        self.conf_record_name.setObjectName("conf_record_name")
        self.horizontalLayout_2.addWidget(self.conf_record_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.conf_record_video_codec = QtGui.QLineEdit(self.groupBox)
        self.conf_record_video_codec.setEnabled(False)
        self.conf_record_video_codec.setObjectName("conf_record_video_codec")
        self.horizontalLayout_3.addWidget(self.conf_record_video_codec)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.conf_record_audio_codec = QtGui.QLineEdit(self.groupBox)
        self.conf_record_audio_codec.setEnabled(False)
        self.conf_record_audio_codec.setObjectName("conf_record_audio_codec")
        self.horizontalLayout_3.addWidget(self.conf_record_audio_codec)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conf_av_chk = QtGui.QCheckBox(self.groupBox_8)
        self.conf_av_chk.setChecked(True)
        self.conf_av_chk.setObjectName("conf_av_chk")
        self.verticalLayout.addWidget(self.conf_av_chk)
        self.conf_audio_only_chk = QtGui.QCheckBox(self.groupBox_8)
        self.conf_audio_only_chk.setEnabled(True)
        self.conf_audio_only_chk.setChecked(False)
        self.conf_audio_only_chk.setObjectName("conf_audio_only_chk")
        self.verticalLayout.addWidget(self.conf_audio_only_chk)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.record_start_btn = QtGui.QPushButton(self.groupBox_2)
        self.record_start_btn.setObjectName("record_start_btn")
        self.verticalLayout_7.addWidget(self.record_start_btn)
        self.record_stop_btn = QtGui.QPushButton(self.groupBox_2)
        self.record_stop_btn.setEnabled(False)
        self.record_stop_btn.setObjectName("record_stop_btn")
        self.verticalLayout_7.addWidget(self.record_stop_btn)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setMargin(1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_7 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.flux_host = QtGui.QLineEdit(self.groupBox_7)
        self.flux_host.setObjectName("flux_host")
        self.horizontalLayout_9.addWidget(self.flux_host)
        self.tcp_enable_conf = QtGui.QCheckBox(self.groupBox_7)
        self.tcp_enable_conf.setObjectName("tcp_enable_conf")
        self.horizontalLayout_9.addWidget(self.tcp_enable_conf)
        self.flux_btn = QtGui.QPushButton(self.groupBox_7)
        self.flux_btn.setEnabled(False)
        self.flux_btn.setObjectName("flux_btn")
        self.horizontalLayout_9.addWidget(self.flux_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_21.addWidget(self.label_12)
        self.flux_video_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_video_port.setObjectName("flux_video_port")
        self.horizontalLayout_21.addWidget(self.flux_video_port)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_22.addWidget(self.label_13)
        self.flux_audio_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_audio_port.setEnabled(True)
        self.flux_audio_port.setObjectName("flux_audio_port")
        self.horizontalLayout_22.addWidget(self.flux_audio_port)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        self.flux_audio_only_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_audio_only_port.setEnabled(False)
        self.flux_audio_only_port.setObjectName("flux_audio_only_port")
        self.horizontalLayout_23.addWidget(self.flux_audio_only_port)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.logtab = QtGui.QTabWidget(self.groupBox_3)
        self.logtab.setEnabled(True)
        self.logtab.setObjectName("logtab")
        self.tab = QtGui.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.log_record = QtGui.QTextEdit(self.tab)
        self.log_record.setUndoRedoEnabled(False)
        self.log_record.setReadOnly(True)
        self.log_record.setAcceptRichText(False)
        self.log_record.setObjectName("log_record")
        self.verticalLayout_9.addWidget(self.log_record)
        self.logtab.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.log_producer_audio2 = QtGui.QTextEdit(self.tab_2)
        self.log_producer_audio2.setUndoRedoEnabled(False)
        self.log_producer_audio2.setReadOnly(True)
        self.log_producer_audio2.setAcceptRichText(False)
        self.log_producer_audio2.setObjectName("log_producer_audio2")
        self.verticalLayout_12.addWidget(self.log_producer_audio2)
        self.logtab.addTab(self.tab_2, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.log_flux = QtGui.QTextEdit(self.tab_5)
        self.log_flux.setUndoRedoEnabled(False)
        self.log_flux.setReadOnly(True)
        self.log_flux.setAcceptRichText(False)
        self.log_flux.setObjectName("log_flux")
        self.verticalLayout_13.addWidget(self.log_flux)
        self.logtab.addTab(self.tab_5, "")
        self.verticalLayout_4.addWidget(self.logtab)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.logtab.setCurrentIndex(0)
        QtCore.QObject.connect(self.flux_btn, QtCore.SIGNAL("clicked()"), MainWindow.onFluxCmd)
        QtCore.QObject.connect(self.conf_av_chk, QtCore.SIGNAL("stateChanged(int)"), MainWindow.onOptionsSwitch)
        QtCore.QObject.connect(self.conf_audio_only_chk, QtCore.SIGNAL("stateChanged(int)"), MainWindow.onOptionsSwitch)
        QtCore.QObject.connect(self.logtab, QtCore.SIGNAL("currentChanged(int)"), MainWindow.onTabSwitch)
        QtCore.QObject.connect(self.record_start_btn, QtCore.SIGNAL("clicked()"), MainWindow.onRecordStart)
        QtCore.QObject.connect(self.record_stop_btn, QtCore.SIGNAL("clicked()"), MainWindow.onRecordStop)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pipes", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Record Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Record Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_record_name.setText(QtGui.QApplication.translate("MainWindow", "capture", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Video Codec:", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_record_video_codec.setText(QtGui.QApplication.translate("MainWindow", "mpeg2video", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec:", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_record_audio_codec.setText(QtGui.QApplication.translate("MainWindow", "mp2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Enable Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_av_chk.setText(QtGui.QApplication.translate("MainWindow", "Audio and Video", None, QtGui.QApplication.UnicodeUTF8))
        self.conf_audio_only_chk.setText(QtGui.QApplication.translate("MainWindow", "Audio Only", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.record_start_btn.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.record_stop_btn.setText(QtGui.QApplication.translate("MainWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Flux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Destination Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.flux_host.setText(QtGui.QApplication.translate("MainWindow", "localhost", None, QtGui.QApplication.UnicodeUTF8))
        self.tcp_enable_conf.setText(QtGui.QApplication.translate("MainWindow", "TCP", None, QtGui.QApplication.UnicodeUTF8))
        self.flux_btn.setText(QtGui.QApplication.translate("MainWindow", "START", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "AV Video Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.flux_video_port.setText(QtGui.QApplication.translate("MainWindow", "1900", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "AV Audio Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.flux_audio_port.setText(QtGui.QApplication.translate("MainWindow", "1902", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Audio Only Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.flux_audio_only_port.setText(QtGui.QApplication.translate("MainWindow", "1904", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.logtab.setTabText(self.logtab.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "AV Producer", None, QtGui.QApplication.UnicodeUTF8))
        self.logtab.setTabText(self.logtab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Audio Only Producer", None, QtGui.QApplication.UnicodeUTF8))
        self.logtab.setTabText(self.logtab.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Flux", None, QtGui.QApplication.UnicodeUTF8))

