# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipes.ui'
#
# Created: Tue Aug 27 20:07:10 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(746, 586)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.conf_record_name = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conf_record_name.sizePolicy().hasHeightForWidth())
        self.conf_record_name.setSizePolicy(sizePolicy)
        self.conf_record_name.setText(_fromUtf8(""))
        self.conf_record_name.setObjectName(_fromUtf8("conf_record_name"))
        self.horizontalLayout_2.addWidget(self.conf_record_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.conf_record_name_2 = QtGui.QLineEdit(self.groupBox)
        self.conf_record_name_2.setObjectName(_fromUtf8("conf_record_name_2"))
        self.horizontalLayout_3.addWidget(self.conf_record_name_2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.date = QtGui.QDateEdit(self.groupBox)
        self.date.setObjectName(_fromUtf8("date"))
        self.horizontalLayout_3.addWidget(self.date)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_8 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.conf_av_chk = QtGui.QCheckBox(self.groupBox_8)
        self.conf_av_chk.setChecked(True)
        self.conf_av_chk.setObjectName(_fromUtf8("conf_av_chk"))
        self.verticalLayout.addWidget(self.conf_av_chk)
        self.conf_audio_only_chk = QtGui.QCheckBox(self.groupBox_8)
        self.conf_audio_only_chk.setEnabled(True)
        self.conf_audio_only_chk.setChecked(False)
        self.conf_audio_only_chk.setObjectName(_fromUtf8("conf_audio_only_chk"))
        self.verticalLayout.addWidget(self.conf_audio_only_chk)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.record_start_btn = QtGui.QPushButton(self.groupBox_2)
        self.record_start_btn.setObjectName(_fromUtf8("record_start_btn"))
        self.verticalLayout_7.addWidget(self.record_start_btn)
        self.record_stop_btn = QtGui.QPushButton(self.groupBox_2)
        self.record_stop_btn.setEnabled(False)
        self.record_stop_btn.setObjectName(_fromUtf8("record_stop_btn"))
        self.verticalLayout_7.addWidget(self.record_stop_btn)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_14.setMargin(1)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupBox_7 = QtGui.QGroupBox(self.frame_3)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_9.addWidget(self.label_3)
        self.flux_host = QtGui.QLineEdit(self.groupBox_7)
        self.flux_host.setObjectName(_fromUtf8("flux_host"))
        self.horizontalLayout_9.addWidget(self.flux_host)
        self.tcp_enable_conf = QtGui.QCheckBox(self.groupBox_7)
        self.tcp_enable_conf.setObjectName(_fromUtf8("tcp_enable_conf"))
        self.horizontalLayout_9.addWidget(self.tcp_enable_conf)
        self.flux_btn = QtGui.QPushButton(self.groupBox_7)
        self.flux_btn.setEnabled(False)
        self.flux_btn.setObjectName(_fromUtf8("flux_btn"))
        self.horizontalLayout_9.addWidget(self.flux_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_21.addWidget(self.label_12)
        self.flux_video_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_video_port.setObjectName(_fromUtf8("flux_video_port"))
        self.horizontalLayout_21.addWidget(self.flux_video_port)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_13 = QtGui.QLabel(self.groupBox_7)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_22.addWidget(self.label_13)
        self.flux_audio_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_audio_port.setEnabled(True)
        self.flux_audio_port.setObjectName(_fromUtf8("flux_audio_port"))
        self.horizontalLayout_22.addWidget(self.flux_audio_port)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_23.addWidget(self.label_14)
        self.flux_audio_only_port = QtGui.QLineEdit(self.groupBox_7)
        self.flux_audio_only_port.setEnabled(False)
        self.flux_audio_only_port.setObjectName(_fromUtf8("flux_audio_only_port"))
        self.horizontalLayout_23.addWidget(self.flux_audio_only_port)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_21)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(2, 0, 2, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.logtab = QtGui.QTabWidget(self.groupBox_3)
        self.logtab.setEnabled(True)
        self.logtab.setObjectName(_fromUtf8("logtab"))
        self.tab = QtGui.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.log_record = QtGui.QTextEdit(self.tab)
        self.log_record.setUndoRedoEnabled(False)
        self.log_record.setReadOnly(True)
        self.log_record.setAcceptRichText(False)
        self.log_record.setObjectName(_fromUtf8("log_record"))
        self.verticalLayout_9.addWidget(self.log_record)
        self.logtab.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.log_producer_audio2 = QtGui.QTextEdit(self.tab_2)
        self.log_producer_audio2.setUndoRedoEnabled(False)
        self.log_producer_audio2.setReadOnly(True)
        self.log_producer_audio2.setAcceptRichText(False)
        self.log_producer_audio2.setObjectName(_fromUtf8("log_producer_audio2"))
        self.verticalLayout_12.addWidget(self.log_producer_audio2)
        self.logtab.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.log_flux = QtGui.QTextEdit(self.tab_5)
        self.log_flux.setUndoRedoEnabled(False)
        self.log_flux.setReadOnly(True)
        self.log_flux.setAcceptRichText(False)
        self.log_flux.setObjectName(_fromUtf8("log_flux"))
        self.verticalLayout_13.addWidget(self.log_flux)
        self.logtab.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.logtab)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 746, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.logtab.setCurrentIndex(0)
        QtCore.QObject.connect(self.flux_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.onFluxCmd)
        QtCore.QObject.connect(self.conf_av_chk, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.onOptionsSwitch)
        QtCore.QObject.connect(self.conf_audio_only_chk, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), MainWindow.onOptionsSwitch)
        QtCore.QObject.connect(self.logtab, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.onTabSwitch)
        QtCore.QObject.connect(self.record_start_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.onRecordStart)
        QtCore.QObject.connect(self.record_stop_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.onRecordStop)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Pipes", None))
        self.groupBox.setTitle(_translate("MainWindow", "Record Options", None))
        self.label_2.setText(_translate("MainWindow", "İsim 1", None))
        self.label.setText(_translate("MainWindow", "İsim 2", None))
        self.label_4.setText(_translate("MainWindow", "Tarih", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Enable Streaming", None))
        self.conf_av_chk.setText(_translate("MainWindow", "Audio and Video", None))
        self.conf_audio_only_chk.setText(_translate("MainWindow", "Audio Only", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Record", None))
        self.record_start_btn.setText(_translate("MainWindow", "START", None))
        self.record_stop_btn.setText(_translate("MainWindow", "STOP", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Flux", None))
        self.label_3.setText(_translate("MainWindow", "Destination Host:", None))
        self.flux_host.setText(_translate("MainWindow", "localhost", None))
        self.tcp_enable_conf.setText(_translate("MainWindow", "TCP", None))
        self.flux_btn.setText(_translate("MainWindow", "START", None))
        self.label_12.setText(_translate("MainWindow", "AV Video Port:", None))
        self.flux_video_port.setText(_translate("MainWindow", "1900", None))
        self.label_13.setText(_translate("MainWindow", "AV Audio Port:", None))
        self.flux_audio_port.setText(_translate("MainWindow", "1902", None))
        self.label_14.setText(_translate("MainWindow", "Audio Only Port:", None))
        self.flux_audio_only_port.setText(_translate("MainWindow", "1904", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Logs", None))
        self.logtab.setTabText(self.logtab.indexOf(self.tab), _translate("MainWindow", "AV Producer", None))
        self.logtab.setTabText(self.logtab.indexOf(self.tab_2), _translate("MainWindow", "Audio Only Producer", None))
        self.logtab.setTabText(self.logtab.indexOf(self.tab_5), _translate("MainWindow", "Flux", None))

